# Generated by Django 3.2.5 on 2023-08-25 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='analise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_atividade', models.BooleanField()),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fim', models.DateTimeField(default=django.utils.timezone.now)),
                ('flag_atualizacao', models.CharField(blank=True, choices=[('Desatualizado', 'Desatualizado'), ('Atualizando', 'Atualizando'), ('Atualizado', 'Atualizado'), ('Erro', 'Erro')], default='Desatualizado', max_length=15, null=True)),
                ('prioridade_atualizacao', models.CharField(blank=True, choices=[('Alta', 'Alta'), ('Baixa', 'Baixa')], default='Alta', max_length=5, null=True)),
                ('grandeza_especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.grandeza_especialista')),
                ('poco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.poco')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='amostra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_coleta', models.CharField(choices=[('PI', 'PI'), ('MANUAL', 'MANUAL'), ('SIMULADA', 'SIMULADA')], default='PI', max_length=8)),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fim', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('NORMAL', 'NORMAL'), ('TRANSIENT', 'TRANSIENT'), ('STEADY STATE', 'STEADY STATE'), ('UNKNOWN', 'UNKNOWN')], default='NORMAL', max_length=30)),
                ('estado_poco', models.CharField(choices=[('OPEN', 'OPEN'), ('SHUT-IN', 'SHUT-IN'), ('FLUSHING DIESEL', 'FLUSHING DIESEL'), ('FLUSHING GAS', 'FLUSHING GAS'), ('BULLHEADING', 'BULLHEADING'), ('CLOSED WITH DIESEL', 'CLOSED WITH DIESEL'), ('CLOSED WITH GAS', 'CLOSED WITH GAS'), ('RESTART', 'RESTART'), ('DEPRESSURIZATION', 'DEPRESSURIZATION'), ('UNKNOWN', 'UNKNOWN')], default='OPEN', max_length=30)),
                ('analise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor_app.analise')),
            ],
        ),
    ]
