# Generated by Django 3.2.5 on 2023-12-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analise',
            old_name='status_atividade',
            new_name='exportacao_habilitada',
        ),
        migrations.RemoveField(
            model_name='amostra',
            name='tipo_coleta',
        ),
        migrations.RemoveField(
            model_name='analise',
            name='flag_atualizacao',
        ),
        migrations.RemoveField(
            model_name='analise',
            name='prioridade_atualizacao',
        ),
        migrations.AddField(
            model_name='analise',
            name='status_exportacao',
            field=models.CharField(blank=True, choices=[('Pendente', 'Pendente'), ('Exportando', 'Exportando'), ('Exportada', 'Exportada'), ('Erro', 'Erro')], default='Pendente', max_length=15, null=True),
        ),
    ]
