# Generated by Django 5.0.3 on 2025-01-03 23:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "admin_app",
            "0008_grandeza_especialista_perf_grandeza_industrial_perf_and_more",
        ),
        ("monitor_app", "0002_auto_20231202_2042"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="servidor_perf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="sonda_perf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="analise_perf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_registro",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "data_inicio",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("data_fim", models.DateTimeField(default=django.utils.timezone.now)),
                ("exportacao_habilitada", models.BooleanField()),
                (
                    "status_exportacao",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Exportando", "Exportando"),
                            ("Exportada", "Exportada"),
                            ("Erro", "Erro"),
                        ],
                        default="Pendente",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "grandeza_especialista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_app.grandeza_especialista_perf",
                    ),
                ),
                (
                    "poco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_app.poco_perf",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "servidor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitor_app.servidor_perf",
                    ),
                ),
                (
                    "sonda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitor_app.sonda_perf",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="amostra_perf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inicio", models.DateTimeField(default=django.utils.timezone.now)),
                ("fim", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("NORMAL", "NORMAL"),
                            ("TRANSIENT", "TRANSIENT"),
                            ("STEADY STATE", "STEADY STATE"),
                            ("UNKNOWN", "UNKNOWN"),
                        ],
                        default="NORMAL",
                        max_length=30,
                    ),
                ),
                (
                    "analise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitor_app.analise_perf",
                    ),
                ),
            ],
        ),
    ]
