# Generated by Django 5.1.7 on 2025-03-31 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitor_app", "0004_lookup_servidor_perf"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="lookup_servidor_perf",
            unique_together={("sonda", "servidor")},
        ),
    ]
