# Generated by Django 3.2.5 on 2023-08-25 22:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='grandeza_especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('codigo_faixanormal', models.IntegerField(blank=True, default=0, null=True)),
                ('codigo_faixatransiente', models.IntegerField(blank=True, default=0, null=True)),
                ('codigo_faixaestabelecida', models.IntegerField(blank=True, default=0, null=True)),
                ('normalidade_min', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='grandeza_industrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='unidade_medida_padrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='uo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='unidade_medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('coeficiente_angular', models.FloatField(blank=True, null=True)),
                ('coeficiente_linear', models.FloatField(blank=True, null=True)),
                ('unidade_medida_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.unidade_medida_padrao')),
            ],
        ),
        migrations.CreateModel(
            name='uep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('ativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.ativo')),
            ],
        ),
        migrations.CreateModel(
            name='poco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('is_font_vip_xlsx', models.BooleanField(default=True)),
                ('is_font_vip_api', models.BooleanField(default=True)),
                ('uep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.uep')),
            ],
        ),
        migrations.AddField(
            model_name='ativo',
            name='uo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.uo'),
        ),
        migrations.CreateModel(
            name='variavel_industrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('is_font_pi_system', models.BooleanField(default=True)),
                ('is_af', models.BooleanField(default=False)),
                ('servidor_pi', models.CharField(blank=True, max_length=50, null=True)),
                ('tag', models.CharField(blank=True, max_length=500, null=True)),
                ('status_atividade', models.BooleanField(blank=True, null=True)),
                ('data_registro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('data_inicio', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('data_fim', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('grandeza_industrial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.grandeza_industrial')),
                ('poco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.poco')),
                ('um', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.unidade_medida')),
            ],
            options={
                'unique_together': {('grandeza_industrial', 'poco')},
            },
        ),
        migrations.CreateModel(
            name='relacao_especialista_industrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.grandeza_especialista')),
                ('industrial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.grandeza_industrial')),
            ],
            options={
                'unique_together': {('especialista', 'industrial')},
            },
        ),
    ]
