# Generated by Django 3.2.5 on 2023-12-02 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variavel_industrial',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='variavel_industrial',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='variavel_industrial',
            name='data_registro',
        ),
        migrations.RemoveField(
            model_name='variavel_industrial',
            name='status_atividade',
        ),
    ]
