# Generated by Django 3.2.5 on 2024-01-12 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_auto_20231202_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grandeza_especialista',
            old_name='codigo_faixanormal',
            new_name='rotulo_normalidade',
        ),
        migrations.RenameField(
            model_name='grandeza_especialista',
            old_name='codigo_faixaestabelecida',
            new_name='rotulo_steady_state',
        ),
        migrations.RenameField(
            model_name='grandeza_especialista',
            old_name='codigo_faixatransiente',
            new_name='rotulo_transient',
        ),
    ]
