# Generated by Django 3.2.5 on 2024-01-12 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_auto_20240112_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grandeza_especialista',
            old_name='normalidade_min',
            new_name='periodo_amostra_inicial_nao_rotulada',
        ),
    ]
