# Generated by Django 3.2.5 on 2024-02-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_rename_normalidade_min_grandeza_especialista_periodo_amostra_inicial_nao_rotulada'),
    ]

    operations = [
        migrations.AddField(
            model_name='poco',
            name='is_not_font_vip_api_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poco',
            name='is_not_font_vip_api_obs',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='poco',
            name='is_not_font_vip_xlsx_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poco',
            name='is_not_font_vip_xlsx_obs',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='variavel_industrial',
            name='is_not_font_pi_system_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variavel_industrial',
            name='is_not_font_pi_system_obs',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
