# Generated by Django 5.0.3 on 2024-04-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0005_auto_20240208_2038"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variavel_industrial",
            name="is_af",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="variavel_industrial",
            name="is_font_pi_system",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
