# Generated by Django 5.0.3 on 2024-05-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_alter_variavel_industrial_is_af_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poco',
            name='is_font_vip_api',
        ),
        migrations.RemoveField(
            model_name='poco',
            name='is_not_font_vip_api_date',
        ),
        migrations.RemoveField(
            model_name='poco',
            name='is_not_font_vip_api_obs',
        ),
        migrations.AddField(
            model_name='variavel_industrial',
            name='is_font_vip_api',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variavel_industrial',
            name='is_not_font_vip_api_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variavel_industrial',
            name='is_not_font_vip_api_obs',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
