# Generated by Django 5.0.3 on 2025-01-03 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0007_remove_poco_is_font_vip_api_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="grandeza_especialista_perf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
                (
                    "rotulo_normalidade",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "rotulo_transient",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "rotulo_steady_state",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="grandeza_industrial_perf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="poco_perf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="uo_perf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ativo_perf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
                (
                    "uo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_app.uo_perf",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="relacao_especialista_industrial_perf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "especialista",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_app.grandeza_especialista_perf",
                    ),
                ),
                (
                    "industrial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_app.grandeza_industrial_perf",
                    ),
                ),
            ],
            options={
                "unique_together": {("especialista", "industrial")},
            },
        ),
        migrations.CreateModel(
            name="variavel_industrial_perf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "grandeza_industrial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_app.grandeza_industrial_perf",
                    ),
                ),
                (
                    "poco",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_app.poco_perf",
                    ),
                ),
            ],
            options={
                "unique_together": {("grandeza_industrial", "poco")},
            },
        ),
    ]
