# Generated by Django 5.0.3 on 2025-01-04 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "admin_app",
            "0008_grandeza_especialista_perf_grandeza_industrial_perf_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="poco_perf",
            name="ativo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="admin_app.ativo_perf",
            ),
        ),
    ]
