# Generated by Django 5.0.3 on 2025-01-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0009_poco_perf_ativo"),
    ]

    operations = [
        migrations.AddField(
            model_name="grandeza_especialista_perf",
            name="periodo_amostra_inicial_nao_rotulada",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="grandeza_industrial_perf",
            name="descricao",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
