# Generated by Django 5.0.3 on 2025-01-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "admin_app",
            "0010_grandeza_especialista_perf_periodo_amostra_inicial_nao_rotulada_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="grandeza_industrial_perf",
            name="localizacao",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="grandeza_industrial_perf",
            name="origem",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="grandeza_industrial_perf",
            name="um",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
